routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::group(['prefix' => '/demo','namespace' => '\App\Http\Controllers'], function () {
    Route::get('/', 'SiteController@renderHomePage');
    Route::get('/services', 'SiteController@renderServicesPage');
    Route::get('/articles/{cgy}', 'SiteController@renderCgyArticlesPage');
    Route::get('/article/{article}', 'SiteController@renderArticlePage');
    Route::get('/about', 'SiteController@renderAboutPage');
    Route::get('/contact', 'SiteController@renderContactPage');
    Route::get('/thank', 'SiteController@renderThankPage');
    Route::get('/policy', 'SiteController@renderPolicyPage');
    Route::get('/portfolio','SiteController@renderPortfolioPage');
    Route::get('/portfolio/{media}', 'SiteController@renderPortfolioDetailPage');

    Route::post('/save','SiteController@save');
});

Route::get('/','\App\Http\Controllers\SiteController@renderWelcomePage');


//自定義後台路由規則
Route::group(['prefix' => 'admin', 'namespace' => '\App\Http\Controllers', 'middleware' => ['web', 'javck.roleCheck', 'javck.verifyEnabled']], function () {
});

Route::get('/demo/hello','\App\Http\Controllers\homecontroller@about');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Voyager;

//用來儲存文章的回應

class Comment extends Model
{
    protected $guarded = [];

    public function user()
    {
    	return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    public function article()
    {
        return $this->belongsTo('App\Models\Article', 'article_id', 'id');
    }

    public function getPicAttribute(){
    	if (isset($this->user)) {
    		return $this->user->pic;
    	} else {
    		return 'avator.png';
    	}

    }

    public function getNameAttribute($value)
    {
    	if ($value != null and strlen($value) > 0) {
    		return $value;
    	} else {
    		return "匿名者";
    	}

    }

    public function getReplysAttribute()
    {
        $replys = Comment::where('reply_to',$this->id)->where('enabled',1)->orderBy('created_at','desc')->get();
        if ($replys != null && count($replys) > 0) {
            return $replys;
        } else {
            return array();
        }

    }

    public function getReplied()
    {
        $reply_count = Comment::where('reply_to',$this->id)->where('enabled',1)->count();
        if ($reply_count == 0) {
            return '尚未';
        } else {
            return '完成';
        }

    }

    public function getEnabled(){
        if ($this->enabled == true) {
            return '是';
        }else{
            return '否';
        }
    }

    /**
     * 限制查詢只包括某種啟動狀態的元素。
     *
     * @return \Illuminate\Database\Eloquent\Builder
     * @param enabled 文件啟動狀態
     */
    public function scopeEnabled( $query , $enabled )
    {
        if ($enabled != 'none') {
            return $query->where('enabled',$enabled );
        }else{
            return $query;
        }
    }

    /**
     * 限制查詢只包括某種回覆狀態的元素。
     *
     * @return \Illuminate\Database\Eloquent\Builder
     * @param isReply 文件回覆狀態
     */
    public function scopeIsReply( $query , $isReply )
    {
        if ($isReply != 'none') {
            $acs = Comment::where('enabled',1)->whereNotNull('reply_to')->distinct('reply_to')->pluck('reply_to')->toArray();
            //dd([5,6,7]);
            if ($isReply == "1") {
                return $query->whereIn('id',$acs);
            } else {
                return $query->whereNull('reply_to')->whereNotIn('id',$acs);
            }
        }else{
            return $query;
        }
    }
}

resources/views/menu/classic.blade.php
<nav id="primary-menu" class="{{ setting('canvas.pri_menu_class') }}">
	<ul>
	    @foreach($items as $menu_item)
	    	@if ($menu_item->link() == '#modal-login')
	    		@if (!Auth::check())
					<li class="menu-item-emphasis"><a href="#modal-login" data-lightbox="inline"><div>{{ $menu_item->title }}</div></a></li>
				@else
					<li class=""><a href="{{url('/admin')}}"><div>歡迎,{{ Auth::user()->name }}</div></a></li>
	    		@endif
	   			
	    		@php
	    			continue;
	    		@endphp
	    	@endif
	    	@if (substr( $menu_item->link(), 0, 1 ) === "#")
	    		<li><a href="#" data-href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a>
	    	@else
	    		<li><a class="{{ Request::is($menu_item->link())? 'current' : ''}}" href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a>
	    	@endif
        	@php
	            $submenu = $menu_item->children;
	        @endphp

		    @if(isset($submenu) && count($submenu) > 0)
	            <ul>
	                @foreach($submenu as $item)
	                    <li><a href="{{$item->link()}}">{{$item->title}} </a>
		                    @php
					            $sub2menu = $item->children;
					        @endphp

					        @if(isset($sub2menu) && count($sub2menu) > 0)
					            <ul>
					                @foreach($sub2menu as $sub2_item)
					                    <li><a href="{{$sub2_item->link()}}">{{$sub2_item->title}} </a></li>
					                    
					                @endforeach
					            </ul>
					        @endif
				        </li>
	                @endforeach
	            </ul>
		    @endif
	        </li>
	    @endforeach
	</ul>
</nav>

resources/views/menu/menu_footer.blade.php
@foreach($items as $menu_item)
    <a href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a> @if(!$loop->last)/@endif
@endforeach